---
- name: Install JAVA
  apt: name=default-jdk state=present

- name: Add Group "tomcat"
  group: name=tomcat

- name: Add User "tomcat"
  become: True
  become_method: sudo
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no

- name: Create a Tomcat Directory
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: '0755'
    recurse: yes

- name: Download Tomcat
  get_url: url={{ tomcat_archive_url }} dest={{ tomcat_archive_dest }}

- name: Unarchive Tomcat
  become: True
  become_method: sudo
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: '0755'
    extra_opts: [--strip-components=1]
    remote_src: yes 

- name: Copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: Set UI access credentials
  template:
    src: templates/tomcat-users.xml.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
  notify: restart tomcat

- name: Allow access to Manager and Host Manager apps from any IP
  template:
    src: templates/context.xml.j2 
    dest: "{{ item }}"
  with_items:
    - /opt/tomcat/webapps/host-manager/META-INF/context.xml
    - /opt/tomcat/webapps/manager/META-INF/context.xml
  notify: restart tomcat